import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# Keycloak setup
OIDC_OP_JWKS_ENDPOINT = os.environ.get('OIDC_OP_JWKS_ENDPOINT')
OIDC_RP_SIGN_ALGO = os.environ.get('OIDC_RP_SIGN_ALGO')
OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET')
OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get('OIDC_OP_AUTHORIZATION_ENDPOINT')
OIDC_OP_LOGOUT_ENDPOINT = os.environ.get('OIDC_OP_LOGOUT_ENDPOINT')
OIDC_OP_ENDSESSION_ENDPOINT = os.environ.get('OIDC_OP_ENDSESSION_ENDPOINT')
OIDC_OP_LOGOUT_URL_METHOD = os.environ.get('OIDC_OP_LOGOUT_URL_METHOD')
OIDC_OP_TOKEN_ENDPOINT = os.environ.get('OIDC_OP_TOKEN_ENDPOINT')
OIDC_OP_USER_ENDPOINT = os.environ.get('OIDC_OP_USER_ENDPOINT')
OIDC_CALLBACK_PUBLIC_URI = "http://localhost:8080"

LOGIN_REDIRECT_URL = OIDC_CALLBACK_PUBLIC_URI
LOGOUT_REDIRECT_URL = OIDC_CALLBACK_PUBLIC_URI

KEYCLOAK_ADMIN_USERNAME = os.environ.get('KEYCLOAK_USERNAME')
KEYCLOAK_ADMIN_PASSWORD = os.environ.get('KEYCLOAK_USER_PASSWORD')

KEYCLOAK_CONFIG = {
    'KEYCLOAK_SERVER_URL': os.environ.get('KEYCLOAK_SERVER_URL'),
    'KEYCLOAK_REALM': os.environ.get('OIDC_RP_REALM_ID'),
    'KEYCLOAK_CLIENT_ID': os.environ.get('OIDC_RP_CLIENT_ID'),
    'KEYCLOAK_CLIENT_SECRET_KEY': os.environ.get('OIDC_RP_CLIENT_SECRET')
}

# Blockchain setup
BLOCKCHAIN_CONFIG = {
    'BLOCKCHAIN_RPC_URL': os.environ.get('BLOCKCHAIN_RPC_URL'),
    'BLOCKCHAIN_PRIVATE_KEY': os.environ.get('BLOCKCHAIN_PRIVATE_KEY'),
    'BLOCKCHAIN_CONTRACTS_ROOT_PATH': os.environ.get("CONTRACTS_ROOT_PATH", BASE_DIR / "contracts"),
    'POLICY_INFORMATION_POINT_ADDRESS': os.environ.get('POLICY_INFORMATION_POINT_ADDRESS'),
    'POLICY_ADMINISTRATION_POINT_ADDRESS': os.environ.get('POLICY_ADMINISTRATION_POINT_ADDRESS'),
    'POLICY_DECISION_POINT_ADDRESS': os.environ.get('POLICY_DECISION_POINT_ADDRESS')
}