name: CD prod 🚀
run-name: Continuous Delivery to PROD environment 🚥
on:
  release:
    types: [published]
jobs:
  ci:
    name: ci prod
    uses: ./.github/workflows/ci.yaml
    with:
      image_tag: latest

  build:
    name: Build
    needs: ci
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:latest

  deploy:
    name: Deploy to production 🚀
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      # TODO: Deploy somewhere, e.g. Google Cloud, AWS etc